name: CI

on: [push]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: PHP CS Fixer
        run: |
          exit 0

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: PHPStan
        run: |
          exit 1

  notify:
    runs-on: ubuntu-latest
    needs: [phpcs, phpstan]
    if: always()
    steps:
      - name: Slack Notify
        uses: baijunyao/action-slack-notify@feature/merge-notify
        if: always()
        with:
          slack_channel_id: CEWJP77BP
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_context: ${{ toJson(github) }}
          job_context: ${{ toJson(job) }}
